#pragma once

#define USE_REGULAR_MC 0
#define SNAP_THRESHOLD 0.5f
#define DELETE_AFTER_EXTRACT 1
#define MAX_TREE_DEPTH 20
#define DEFAULT_FOCUS_POS { 0, 115.2f, 0 }
#define DEFAULT_SUB_RESOLUTION 3
#define SMOOTH_NORMALS 0
